# Generated by Django 5.2.7 on 2025-10-15 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_record_kitob_alter_record_kutubxonachi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='talaba',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.talaba'),
            preserve_default=False,
        ),
    ]
